# Generated by Django 5.1.7 on 2025-03-31 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=100)),
                ('green_desc', models.CharField(max_length=300)),
                ('amber_desc', models.CharField(max_length=300)),
                ('red_desc', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_title', models.CharField(max_length=100)),
                ('survey_description', models.CharField(max_length=300)),
                ('survey_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.survey')),
            ],
            options={
                'db_table': 'SurveyDetail',
                'unique_together': {('survey', 'question')},
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(related_name='surveys', through='voting.SurveyDetail', to='voting.question'),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quarter', models.IntegerField()),
                ('year', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.survey')),
            ],
            options={
                'db_table': 'SurveyResponse',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponseDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('improvement_state', models.CharField(choices=[('stable', 'Stable'), ('improving', 'Improving'), ('getting worse', 'Getting Worse')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.surveyresponse')),
            ],
            options={
                'db_table': 'SurveyResponseDetail',
            },
        ),
    ]
