# Generated by Django 5.1.7 on 2025-04-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.survey')),
            ],
            options={
                'db_table': 'Session',
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.session'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('employee', 'session')},
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='year',
        ),
    ]
