# Generated by Django 5.1.7 on 2025-04-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_session_surveyresponse_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voting.session'),
            preserve_default=False,
        ),
    ]
